services:

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: jrmsu_library
      POSTGRES_USER: jrmsu_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jrmsu_admin -d jrmsu_library"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_ENGINE: postgresql
      DB_NAME: jrmsu_library
      DB_USER: jrmsu_admin
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: "False"
      DISABLE_SSL_REDIRECT: "True"
      ALLOWED_HOSTS: "*"
      ALLOWED_CORS_ORIGINS: "http://localhost:3000,http://localhost:3001,http://192.168.137.1:3000,http://192.168.137.1:3001,http://192.168.6.126:3000,http://192.168.6.126:3001"
    ports:
      - "8000:8000"
    volumes:
      - ./backend/media:/app/media

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000/api
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data: