# Generated by Django 6.0.5 on 2026-06-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Category (e.g., 'administration-manual')",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="managed_files/")),
                ("is_active", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ManagedLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Category (e.g., 'open-access', 'social', 'uopac')",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier (e.g., 'history', 'quality-objectives')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display title for the section", max_length=200
                    ),
                ),
                ("content", models.TextField(help_text="The actual text content")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="PageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        help_text="Where this image belongs (e.g., 'home-hero', 'excellence')",
                        max_length=100,
                    ),
                ),
                ("image", models.ImageField(upload_to="page_images/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["section_key", "order"],
            },
        ),
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        help_text="The path visited (e.g., '/', '/about')",
                        max_length=200,
                    ),
                ),
                ("visited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        help_text="Anonymized hash of visitor IP to distinguish uniques",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "ordering": ["-visited_at"],
            },
        ),
    ]
