# Generated by Django 6.0.5 on 2026-06-29 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0002_managedfile_managedlink_pagecontent_pageimage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newlyacquiredbook",
            options={"ordering": ["-date_encoded"]},
        ),
        migrations.RemoveField(
            model_name="newlyacquiredbook",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="newlyacquiredbook",
            name="description",
        ),
        migrations.RemoveField(
            model_name="newlyacquiredbook",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="newlyacquiredbook",
            name="is_active",
        ),
        migrations.AddField(
            model_name="newlyacquiredbook",
            name="accession_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="newlyacquiredbook",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="newlyacquiredbook",
            name="date_encoded",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name="AcquisitionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("is_display_batch", models.BooleanField(default=False)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("safety_expiry", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.AddField(
            model_name="newlyacquiredbook",
            name="batch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="Features.acquisitionbatch",
            ),
        ),
        migrations.CreateModel(
            name="BatchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("details", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="Features.acquisitionbatch",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
