# Generated by Django 6.0.5 on 2026-06-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0003_alter_newlyacquiredbook_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email Message"),
                    ("RESERVATION", "Reservation Request"),
                ],
                default="EMAIL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNREAD", "Unread"),
                    ("READ", "Read"),
                    ("REPLIED", "Replied"),
                ],
                default="UNREAD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
