# Generated by Django 6.0.5 on 2026-06-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0004_contactmessage_message_type_contactmessage_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "library_name",
                    models.CharField(default="JRMSU Katipunan Library", max_length=255),
                ),
                (
                    "address",
                    models.CharField(
                        default="Katipunan, Zamboanga del Norte", max_length=500
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="katipunan.library@jrmsu.edu.ph", max_length=254
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "opening_hours_mon_fri",
                    models.CharField(default="7:00 AM - 7:00 PM", max_length=100),
                ),
                (
                    "opening_hours_sat",
                    models.CharField(default="Closed", max_length=100),
                ),
                (
                    "opening_hours_sun",
                    models.CharField(default="Closed", max_length=100),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "site_settings",
            },
        ),
    ]
