# Generated by Django 6.0.5 on 2026-07-01 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0005_sitesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNREAD", "Unread"),
                    ("READ", "Read"),
                    ("REPLIED", "Replied"),
                    ("ARCHIVED", "Archived"),
                    ("APPROVED", "Approved"),
                    ("DECLINED", "Declined"),
                ],
                default="UNREAD",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RecycleBin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField()),
                (
                    "source_module",
                    models.CharField(
                        choices=[
                            ("BOOKS", "Newly Acquired Books"),
                            ("GALLERY", "Library Sections"),
                        ],
                        max_length=50,
                    ),
                ),
                ("item_name", models.CharField(max_length=300)),
                (
                    "data_snapshot",
                    models.JSONField(
                        help_text="Serialized data of the deleted item for restoration"
                    ),
                ),
                ("deleted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted_by", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-deleted_at"],
                "indexes": [
                    models.Index(
                        fields=["source_module"], name="Features_re_source__b0c9ec_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="Features_re_deleted_289236_idx"
                    ),
                ],
            },
        ),
    ]
