# Generated by Django 6.0.5 on 2026-07-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0009_seed_actual_ebook_departments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eresourcefile",
            name="file",
            field=models.FileField(max_length=500, upload_to="e_resources/"),
        ),
        migrations.AlterField(
            model_name="eresourcefile",
            name="name",
            field=models.CharField(max_length=500),
        ),
    ]
