# Generated by Django 4.2.30 on 2026-07-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0011_seed_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="carousel_style",
            field=models.CharField(
                choices=[
                    ("default", "Default (3D)"),
                    ("classic", "Classic (Horizontal)"),
                ],
                default="default",
                max_length=20,
            ),
        ),
    ]
