# Generated by Django 4.2.30 on 2026-07-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0012_sitesettings_carousel_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="eresourcefile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
