# Generated by Django 6.0.5 on 2026-07-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0013_eresourcefile_add_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recyclebin",
            name="source_module",
            field=models.CharField(
                choices=[
                    ("BOOKS", "Newly Acquired Books"),
                    ("GALLERY", "Library Sections"),
                    ("BATCH", "Acquisition Batches"),
                ],
                max_length=50,
            ),
        ),
    ]
