# Generated by Django 6.0.5 on 2026-07-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0014_alter_recyclebin_source_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture for this admin user",
                null=True,
                upload_to="avatars/",
            ),
        ),
        migrations.AlterField(
            model_name="recyclebin",
            name="source_module",
            field=models.CharField(
                choices=[
                    ("BOOKS", "Newly Acquired Books"),
                    ("GALLERY", "Library Sections"),
                    ("BATCH", "Acquisition Batches"),
                    ("CMS_CONTENT", "Content Manager (Pages)"),
                    ("CMS_IMAGE", "Content Manager (Images)"),
                    ("CMS_LINK", "Content Manager (Links)"),
                    ("CMS_FILE", "Content Manager (Files)"),
                    ("ERESOURCE_DEPT", "E-Resources (Departments)"),
                    ("ERESOURCE_FILE", "E-Resources (Files)"),
                    ("CONTACT_MSG", "Contact Messages"),
                ],
                max_length=50,
            ),
        ),
    ]
