# Generated by Django 6.0.5 on 2026-07-02 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0015_add_avatar_to_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("report_type", models.CharField(max_length=50)),
                ("date_range", models.CharField(max_length=50)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("report_data", models.JSONField()),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "jrmsu_generated_reports",
                "ordering": ["-generated_at"],
            },
        ),
    ]
