# Generated by Django 6.0.6 on 2026-07-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0016_add_generated_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedreport",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="recyclebin",
            name="source_module",
            field=models.CharField(
                choices=[
                    ("BOOKS", "Newly Acquired Books"),
                    ("GALLERY", "Library Sections"),
                    ("BATCH", "Acquisition Batches"),
                    ("CMS_CONTENT", "Content Manager (Pages)"),
                    ("CMS_IMAGE", "Content Manager (Images)"),
                    ("CMS_LINK", "Content Manager (Links)"),
                    ("CMS_FILE", "Content Manager (Files)"),
                    ("ERESOURCE_DEPT", "E-Resources (Departments)"),
                    ("ERESOURCE_FILE", "E-Resources (Files)"),
                    ("CONTACT_MSG", "Contact Messages"),
                    ("REPORT", "Generated Reports"),
                ],
                max_length=50,
            ),
        ),
    ]
