# Generated by Django 4.2.30 on 2026-07-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0017_generatedreport_is_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="reply_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email Message"),
                    ("RESERVATION", "Reservation Request"),
                    ("CREDENTIAL_REQUEST", "Credential Request"),
                ],
                default="EMAIL",
                max_length=20,
            ),
        ),
    ]
