# Generated by Django 4.2.30 on 2026-07-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Features",
            "0018_contactmessage_replied_at_contactmessage_reply_text_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="last_active",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
