# Generated by Django 4.2.30 on 2026-07-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0019_account_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
    ]
