# Generated by Django 4.2.30 on 2026-07-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0020_sitesettings_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_terminal_created",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this admin was created via the terminal. Such admins cannot be deleted by UI-created admins.",
            ),
        ),
    ]
