# Generated by Django 4.2.30 on 2026-07-20 02:34

import Features.Data.Models.contact_attachment_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0021_account_is_terminal_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=Features.Data.Models.contact_attachment_model.contact_attachment_upload_path
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(help_text="Size in bytes")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="Features.contactmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
    ]
