# Generated by Django 4.2.30 on 2026-07-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0023_alter_contactmessage_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message_type',
            field=models.CharField(choices=[('EMAIL', 'Email Message'), ('RESERVATION', 'Reservation Request'), ('CREDENTIAL_REQUEST', 'Credential Request')], default='EMAIL', max_length=20),
        ),
    ]
