# Generated by Django 4.2.30 on 2026-07-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0024_alter_contactmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
