# Generated by Django 4.2.30 on 2026-07-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0025_feedback_ip_address_feedback_user_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="alternate_email",
            field=models.EmailField(
                blank=True, default="jrmsukclibrary@gmail.com", max_length=254
            ),
        ),
    ]
