# Generated by Django 4.2.30 on 2026-07-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0026_sitesettings_alternate_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="alternate_email",
            field=models.EmailField(
                blank=True,
                default="jrmsukclibrary@gmail.com",
                max_length=254,
                null=True,
            ),
        ),
    ]
