# Generated by Django 4.2.30 on 2026-07-21 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0027_alter_sitesettings_alternate_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Research for College Student in JRMSU', 'Research for College Student in JRMSU'), ('Thesis and Dissertation', 'Thesis and Dissertation')], max_length=255)),
                ('no', models.IntegerField(blank=True, null=True)),
                ('acc_no', models.CharField(blank=True, max_length=255, null=True)),
                ('call_number', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=500, null=True)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('resource_status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'research_references',
                'ordering': ['-created_at'],
            },
        ),
    ]
