# Generated by Django 4.2.30 on 2026-07-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0028_researchreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchreference',
            name='department',
            field=models.CharField(blank=True, choices=[('Research of Bachelor of Science in Forestry (BSF)', 'Research of Bachelor of Science in Forestry (BSF)'), ('Research Books for Bachelor of Science in Computer Science', 'Research Books for Bachelor of Science in Computer Science'), ('Research Books for Agri. Business Management', 'Research Books for Agri. Business Management'), ('Narrative Report of Secondary Education', 'Narrative Report of Secondary Education')], help_text='Only applicable for student research records.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchreference',
            name='inventory_year',
            field=models.CharField(blank=True, help_text='Value from the Inventory column in the Excel import (e.g. "2026").', max_length=100, null=True),
        ),
    ]
