# Generated by Django 4.2.30 on 2026-07-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0029_add_department_inventory_to_research_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchreference',
            name='access_file',
            field=models.FileField(blank=True, null=True, upload_to='research_references/'),
        ),
        migrations.AddField(
            model_name='researchreference',
            name='access_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='researchreference',
            name='access_type',
            field=models.CharField(choices=[('none', 'None'), ('link', 'Online Link'), ('file', 'Uploaded File')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='recyclebin',
            name='source_module',
            field=models.CharField(choices=[('BOOKS', 'Newly Acquired Books'), ('GALLERY', 'Library Sections'), ('BATCH', 'Acquisition Batches'), ('CMS_CONTENT', 'Content Manager (Pages)'), ('CMS_IMAGE', 'Content Manager (Images)'), ('CMS_LINK', 'Content Manager (Links)'), ('CMS_FILE', 'Content Manager (Files)'), ('ERESOURCE_DEPT', 'E-Resources (Departments)'), ('ERESOURCE_FILE', 'E-Resources (Files)'), ('CONTACT_MSG', 'Contact Messages'), ('REPORT', 'Generated Reports'), ('RESEARCH_REF', 'Research References')], max_length=50),
        ),
    ]
