# Generated by Django 4.2.30 on 2026-07-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Features", "0030_researchreference_access_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acquisitionbatch",
            name="last_interacted_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
