# Generated by Django 4.2.30 on 2026-07-22 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0031_acquisitionbatch_last_interacted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquisitionbatch',
            options={'ordering': ['-last_interacted_at', '-opened_at']},
        ),
    ]
