# Generated by Django 4.2.30 on 2026-08-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0035_seed_faq_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='acquisitionbatch',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='acquisitionbatch',
            name='remarks',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='batchhistory',
            name='details',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='reply_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=models.TextField(help_text='The actual text content', max_length=5000),
        ),
        migrations.AlterField(
            model_name='researchreference',
            name='remarks',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
