export interface TreeNodeData {
  name: string;
  type: 'folder' | 'file';
  children?: TreeNodeData[];
  path?: string;
}

const agriPath = '/assets/eBooks/eBooks/Department/AGRI';
const cafPath = '/assets/eBooks/eBooks/Department/CAF';
const ccsPath = '/assets/eBooks/eBooks/Department/CCS';
const ctedPath = '/assets/eBooks/eBooks/Department/CTED';

export const eBooksTree: TreeNodeData[] = [
  {
    name: 'AGRI',
    type: 'folder',
    path: `${agriPath}`,
    children: [
      {
        name: 'BS Agriculture',
        type: 'folder',
        path: `${agriPath}/BS Agriculture`,
        children: [
          { name: '01.-Basic-Agriculture.-Student-Handbook.pdf', type: 'file', path: `${agriPath}/BS Agriculture/01.-Basic-Agriculture.-Student-Handbook-author-Shiksha-Kendra.pdf` },
          { name: '02.-Farmer-s-Handbook-on-Basic-Agriculture.pdf', type: 'file', path: `${agriPath}/BS Agriculture/02.-Farmer-s-Handbook-on-Basic-Agriculture-author-Chandra-Shekara-Ajit-Kumar-N.-Balasubramani-Bakul-C.-Chaudhary-Rajeev-Sharma-Max-Baumann-and-Chitra-Shukla.pdf` },
          { name: '05.-Northeast-Beginning-Farmer_s-Field-Journal.pdf', type: 'file', path: `${agriPath}/BS Agriculture/05.-Northeast-Beginning-Farmer_s-Field-Journal-author-Greenhorns.pdf` },
          { name: '09.-Understanding-Farming.pdf', type: 'file', path: `${agriPath}/BS Agriculture/09.-Understanding-Farming.-Facts-and-figures-about-German-farming-author-Federal-Ministry-of-Food-and-Agriculture-BMEL.pdf` },
          { name: '14.-Teaching-Organic-Farming-Gardening.pdf', type: 'file', path: `${agriPath}/BS Agriculture/14.-Teaching-Organic-Farming-Gardening-author-Martha-Brown-Jan-Perez-and-Albie-Miles.pdf` },
          { name: '15.-Training-manual-for-organic-agriculture.pdf', type: 'file', path: `${agriPath}/BS Agriculture/15.-Training-manual-for-organic-agriculture-author-Nadia-Scialabba-Ilka-Gomez-and-Lisa-Thivant.pdf` },
          { name: '16.-National-Organic-Farming-Handbook.pdf', type: 'file', path: `${agriPath}/BS Agriculture/16.-National-Organic-Farming-Handbook-author-USDA.pdf` },
          { name: '17.-Organic-Food-and-Farming.pdf', type: 'file', path: `${agriPath}/BS Agriculture/17.-Organic-Food-and-Farming-author-Ifoam-EU-Group.pdf` },
          { name: '18.-What-is-Organic-Farming.pdf', type: 'file', path: `${agriPath}/BS Agriculture/18.-What-is-Organic-Farming-author-HDRA.pdf` },
          { name: '20.-Sustainable-Agriculture.pdf', type: 'file', path: `${agriPath}/BS Agriculture/20.-Sustainable-Agriculture-author-Fritz-J.-H-ni-L-szl-Pint-r-and-Hans-R.-Herren.pdf` },
          { name: '21.-Building-Resilience-for-Adaptation-to-Climate-Change.pdf', type: 'file', path: `${agriPath}/BS Agriculture/21.-Building-Resilience-for-Adaptation-to-Climate-Change-in-the-Agriculture-Sector-author-Alexandre-Meybeck-Jussi-Lankoski-Suzanne-Redfern-Nadine-Azzu-and-Vincent-Gitz.pdf` },
          { name: '22.-Agroecology-Best-Practices.pdf', type: 'file', path: `${agriPath}/BS Agriculture/22.-Agroecology-Best-Practices-author-Agrisud-International.pdf` },
          { name: '23.-Approaches-to-Sustainable-Agriculture.pdf', type: 'file', path: `${agriPath}/BS Agriculture/23.-Approaches-to-Sustainable-Agriculture-author-Barbara-Pia-Oberc-and-Alberto-Arroyo-Schnell.pdf` },
          { name: '24.-Farming-Systems-and-Sustainable-Agriculture.pdf', type: 'file', path: `${agriPath}/BS Agriculture/24.-Farming-Systems-and-Sustainable-Agriculture-author-V.-Praveen-Rao-R.-Veeraraghavaiah-S.-Hemalatha-and-B.-Joseph (1).pdf` },
          { name: 'Harvesting-Prosperity-Technology-and-Productivity-Growth.pdf', type: 'file', path: `${agriPath}/BS Agriculture/Harvesting-Prosperity-Technology-and-Productivity-Growth-in-Agriculture-Keith-Fuglie-Madhur-Gautam-Aparajita-Goyal-and-William-F.-Maloney.pdf` },
          { name: 'Indian-Agriculture-after-Independence.pdf', type: 'file', path: `${agriPath}/BS Agriculture/Indian-Agriculture-after-Independence.pdf` },
        ],
      },
    ],
  },
  {
    name: 'CAF',
    type: 'folder',
    path: `${cafPath}`,
    children: [
      {
        name: 'BIOSYSTEM ENGINEERING',
        type: 'folder',
        path: `${cafPath}/BIOSYSTEM ENGINEERING`,
        children: [
          {
            name: '1st year',
            type: 'folder',
            path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year`,
            children: [
              { name: 'AdvancedEngineeringMathematics 10th Ed.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/AdvancedEngineeringMathematics 10th Ed_Erwin Kreyszig_2006.pdf` },
              { name: 'ANIMAL SCIENCE.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/ANIMAL SCIENCE_Andy Baker_1993.pdf` },
              { name: 'CALCULUS MADE EASY.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/CALCULUS MADE EASY_2nd Ed._F.R.S_1914.pdf` },
              { name: 'Calculus1.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/Calculus1_Veselin Jungic_2022.pdf` },
              { name: 'Calculus2.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/Calculus2_Veselin Jungic_2023.pdf` },
              { name: 'Calculus Vol1.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/Calculus_Gilbert Strang_Vol1_2018.pdf` },
              { name: 'COMPUTER AIDED CIVIL ENGINEERING DRAWING LAB MANUAL.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/COMPUTER AIDED CIVIL ENGINEERING DRAWING LAB MANUAL_Mrs. B. Lavanya_2023.pdf` },
              { name: 'COMPUTER AIDED DRAFTING.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/COMPUTER AIDED DRAFTING_Debasish Sen_2022.pdf` },
              { name: 'COMPUTER AIDED DRAWING.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/COMPUTER AIDED DRAWING_Dr.G. Mylsami_2014.pdf` },
              { name: 'Computer Aided Engineering Design.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/Computer Aided Engineering Design _Saxena, Sahay (Springer)_2005.pdf` },
              { name: 'Engineering Mechanics 1 Statics.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/Engineering Mechanics 1 Statics_2nd ed_Dietmar Gross_2013.pdf` },
              { name: 'ENGINEERING MECHANICS STATICS.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/ENGINEERING MECHANICS STATICS_14th EDITION_R.C Hibbeler_2016.pdf` },
              { name: 'FUNDAMENTALS OF SURVEYING.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/FUNDAMENTALS OF SURVEYING_S.K. Roy_1999.pdf` },
              { name: 'Introduction to Biosystem Engineering.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/Introduction to Biosystem Engineering_Nicholas M. Holden_2020.pdf` },
              { name: 'Physics For Scientists and Engineers.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/Physics For Scientists and Engineers With Modern Physics_Raymond A. Serway_2010.pdf` },
              { name: 'PRINCIPLES AND PRACTICE OF SOIL SCIENCE.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/PRINCIPLES AND PRACTICE OF SOIL SCIENCE_Robert E. White_2006.pdf` },
              { name: 'Surveying-for-engineers.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/1st year/Surveying-for-engineers_J. Uren_1994.pdf` },
            ],
          },
          {
            name: '2ND YEAR',
            type: 'folder',
            path: `${cafPath}/BIOSYSTEM ENGINEERING/2ND YEAR`,
            children: [
              { name: 'ABE 101 Intro to Agriculture.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/2ND YEAR/ABE 101 Intro to Agriculture and Bio Enviromental Engineering.pdf` },
              { name: 'BASIC OF THERMODYNAMICS.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/2ND YEAR/BASIC OF THERMODYNAMICS.pdf` },
              { name: 'DIFFERENTIAL EQUATIONS 1.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/2ND YEAR/DIFFERENTIAL EQUATIONS 1.pdf` },
              { name: 'ELEMENTARY DIFFERENTIAL EQUATIONS.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/2ND YEAR/ELEMENTARY DIFFERENTIAL EQUATIONS AND BOUNDARY VALUE PROBLEMS_11th Edition_William E. Boyce_2019.pdf` },
              { name: 'ENGINEERING MECHANICS 2 Mechanics of Materials.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/2ND YEAR/ENGINEERING MECHANICS 2 MECHANICS OF MATERIALS_2nd Edition_Dietmar Gross_2017.pdf` },
              { name: 'ENGINEERING THERMODYNAMICS.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/2ND YEAR/ENGINEERING THERMODYNAMICS_3rd Edition_R.K Rajput_2007.pdf` },
              { name: 'FLUID MECHANICS.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/2ND YEAR/FLUID MECHANICS FUNDAMENTALS AND APPLICATIONS_Yunus A. Cengel_2014.pdf` },
              { name: 'Fundamentals of Engineering Thermodynamics.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/2ND YEAR/Fundamentals of Engineering Thermodynamics_Michael-J.Moran-Howard-N.-Shapiro_2006.pdf` },
              { name: 'Heat Transfer.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/2ND YEAR/Heat Transfer_10th Edition_Jack P. Holman_2010.pdf` },
              { name: 'STRENGTH MATERIALS.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/2ND YEAR/STRENGTH MATERIALS_4th Edition_Dr.R.K Bansal_2009.pdf` },
            ],
          },
          {
            name: '3rd year',
            type: 'folder',
            path: `${cafPath}/BIOSYSTEM ENGINEERING/3rd year`,
            children: [
              { name: 'Agricultural Products Processing.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/3rd year/Agricultural Products Processing and Postharvest Storage_Bengang Wu_2023.pdf` },
              { name: 'CIGR Handbook of Agricultural Engineering Vol III.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/3rd year/CIGR Handbook of Agricultural Engineering Volume III_Bill A. Stout_199.pdf` },
              { name: 'Irrigation and Drainage Engineering.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/3rd year/Irrigation and Drainage Engineering_E. Acha_2002.pdf` },
              { name: 'Research Methodology.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/3rd year/Research Methodology - Methods and Techniques 2004_Dr. Prabhat Pandey_2015.pdf` },
              { name: 'Soil and Water Conservation Engineering.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/3rd year/Soil and Water Conservation Engineering_Dr. A Mishra.pdf` },
            ],
          },
          {
            name: 'Fourth Year',
            type: 'folder',
            path: `${cafPath}/BIOSYSTEM ENGINEERING/Fourth Year`,
            children: [
              { name: 'Agricultural Structures and Mechanization.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/Fourth Year/Agricultural Structures and Mechanization_Jose Perez-Alonzo_2022.pdf` },
              { name: 'Aquaculture Engineering.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/Fourth Year/Aquaculture Engineering_Second Edition_Odd-Ivar Lekang_2013.pdf` },
              { name: 'Engineering Principles of Agricultural Machines.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/Fourth Year/Engineering Principles of Agricultural Machines_2nd Edition_Ajit K Srivastava_2006.pdf` },
              { name: 'Introduction to Food Process Engineering.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/Fourth Year/Introduction to Food Process Engineering_Albert Ibarz_2014.pdf` },
              { name: 'Introduction-to-Food-Engineering 4th Ed.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/Fourth Year/Introduction-to-Food-Engineering_Fourth-Edition_Paul Singh_2009.pdf` },
            ],
          },
          {
            name: 'Other related books for BSABE',
            type: 'folder',
            path: `${cafPath}/BIOSYSTEM ENGINEERING/Other related books for BSABE`,
            children: [
              { name: 'Professional-Ethics-in-Engineering.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/Other related books for BSABE/191BAEE-Professional-Ethics-in-Engineering.pdf` },
              { name: 'CREATING AND SUSTAINING LEARNING COMMUNITY.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/Other related books for BSABE/CREATING AND SUSTAINING LEARNING COMMUNITY.pdf` },
              { name: 'Entrepreneurship Development-I.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/Other related books for BSABE/Entrepreneurship Develoment-I.pdf` },
              { name: 'Industry Immersion Guidebook.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/Other related books for BSABE/Industry Immersion Guidebook (For Dual Education and Training).pdf` },
              { name: 'Technology-Based Entrepreneurship.pdf', type: 'file', path: `${cafPath}/BIOSYSTEM ENGINEERING/Other related books for BSABE/Technology-Based Entrepreneurship.pdf` },
            ],
          },
        ],
      },
    ],
  },
  {
    name: 'CBA',
    type: 'folder',
    path: `${cafPath}/../CBA`,
    children: [
      { name: '(empty)', type: 'file', path: '' },
    ],
  },
  {
    name: 'CCS',
    type: 'folder',
    path: `${ccsPath}`,
    children: [
      {
        name: 'BSCS',
        type: 'folder',
        path: `${ccsPath}/BSCS`,
        children: [
          { name: 'Advances in Computer Science.pdf', type: 'file', path: `${ccsPath}/BSCS/Advances in Computer Science, Engineering and Applications Proceedings of the Second International Conference on Computer Science, Engineering and Applications (ICCSEA 2012).pdf` },
          { name: 'Beginning Android Web Apps Development.pdf', type: 'file', path: `${ccsPath}/BSCS/Beginning Android Web Apps Development- Develop for Android using HTML5, CSS3, and JavaScript.pdf` },
          { name: 'Combinatorial Optimization.pdf', type: 'file', path: `${ccsPath}/BSCS/Combinatorial Optimization- Algorithms and Complexity.pdf` },
          { name: 'Computer Communication, Networking and Internet Security.pdf', type: 'file', path: `${ccsPath}/BSCS/Computer Communication, Networking and Internet Security.pdf` },
          { name: 'Computer Networks.pdf', type: 'file', path: `${ccsPath}/BSCS/Computer Networks.pdf` },
          { name: 'Dark Web- Exploring and Data Mining.pdf', type: 'file', path: `${ccsPath}/BSCS/Dark Web- Exploring and Data Mining the Dark Side of the Web.pdf` },
          { name: 'Data Science for Business.pdf', type: 'file', path: `${ccsPath}/BSCS/Data Science for Business- What you need to know about data mining and data-analytic thinking.pdf` },
          { name: 'Deep Learning for Natural Language Processing.pdf', type: 'file', path: `${ccsPath}/BSCS/Deep Learning for Natural Language Processing.pdf` },
          { name: 'Deep learning- adaptive computation.pdf', type: 'file', path: `${ccsPath}/BSCS/Deep learning- adaptive computation and machine learning.pdf` },
          { name: 'Digital Image Processing.pdf', type: 'file', path: `${ccsPath}/BSCS/Digital Image Processing.pdf` },
          { name: 'Human-computer interaction.pdf', type: 'file', path: `${ccsPath}/BSCS/Human-computer interaction.pdf` },
          { name: 'Information Assurance.pdf', type: 'file', path: `${ccsPath}/BSCS/Information Assurance- Managing Organizational IT Security Risks.pdf` },
          { name: 'Introduction to Artificial Intelligence.pdf', type: 'file', path: `${ccsPath}/BSCS/Introduction to Artificial Intelligence.pdf` },
          { name: 'Introduction to Computer Science.pdf', type: 'file', path: `${ccsPath}/BSCS/Introduction to Computer Science.pdf` },
          { name: 'Introduction to Visual Computing.pdf', type: 'file', path: `${ccsPath}/BSCS/Introduction to Visual Computing - Core Concepts in Computer Vision, Graphics, and Image Processing.pdf` },
          { name: 'Operating System Concepts.pdf', type: 'file', path: `${ccsPath}/BSCS/Operating System Concepts and Basic Linux Commands.pdf` },
          { name: 'Probability and Statistics for Computer Scientists.pdf', type: 'file', path: `${ccsPath}/BSCS/Probability and Statistics for Computer Scientists.pdf` },
          { name: 'Software Engineering- Architecture.pdf', type: 'file', path: `${ccsPath}/BSCS/Software Engineering- Architecture-driven Software Development.pdf` },
          { name: 'Theory of Automata.pdf', type: 'file', path: `${ccsPath}/BSCS/Theory of Automata, Formal Languages and Computation.pdf` },
        ],
      },
      {
        name: 'BSIS',
        type: 'folder',
        path: `${ccsPath}/BSIS`,
        children: [
          { name: 'Data Structures an Algorithms (6 files)', type: 'folder', path: `${ccsPath}/BSIS/Data Structures an Algorithms` },
          { name: 'Discrete Mathematics (5 files)', type: 'folder', path: `${ccsPath}/BSIS/Discrete Mathematics` },
          { name: 'Enterprise Architecture (5 files)', type: 'folder', path: `${ccsPath}/BSIS/Enterprise Architecture` },
          { name: 'Fundamentals of Information Systems (3 files)', type: 'folder', path: `${ccsPath}/BSIS/Fundamentals of Information Systems` },
          { name: 'Fundamentals of Programming (6 files)', type: 'folder', path: `${ccsPath}/BSIS/Fundamentals of Programming` },
          { name: 'Information Management (5 files)', type: 'folder', path: `${ccsPath}/BSIS/Information Management` },
          { name: 'Intermediate Programming (5 files)', type: 'folder', path: `${ccsPath}/BSIS/Intermediate Programming` },
          { name: 'Intro to 2D Animation (5 files)', type: 'folder', path: `${ccsPath}/BSIS/Intro to 2D Animation` },
          { name: 'Introduction to Computing (4 files)', type: 'folder', path: `${ccsPath}/BSIS/Introduction to Computing` },
          { name: 'IT Infrastructure (5 files)', type: 'folder', path: `${ccsPath}/BSIS/IT Infrastructure & Network Techonologies` },
          { name: 'Mathematics in the Modern World (4 files)', type: 'folder', path: `${ccsPath}/BSIS/Mathematics in the Modern World` },
          { name: 'Multimedia Systems (3 files)', type: 'folder', path: `${ccsPath}/BSIS/Multimedia Systems` },
          { name: 'Object Oriented Programming (5 files)', type: 'folder', path: `${ccsPath}/BSIS/Object Oriented Programming` },
          { name: 'PC Troubleshooting and Networking (4 files)', type: 'folder', path: `${ccsPath}/BSIS/PC Troubleshooting and Networking` },
          { name: 'Quantitative Methods (7 files)', type: 'folder', path: `${ccsPath}/BSIS/Quantitative Methods` },
          { name: 'Science, Technology and Society (3 files)', type: 'folder', path: `${ccsPath}/BSIS/Science, Technology and Society` },
          { name: 'Web Systems and Technologies (2 files)', type: 'folder', path: `${ccsPath}/BSIS/Web Systems and Technologies` },
        ],
      },
    ],
  },
  {
    name: 'CTED',
    type: 'folder',
    path: `${ctedPath}`,
    children: [
      {
        name: 'BEED',
        type: 'folder',
        path: `${ctedPath}/BEED`,
        children: [
          { name: 'A Brief History of the English Language.pdf', type: 'file', path: `${ctedPath}/BEED/A Brief History of the English Language and Literature Vol.2.pdf` },
          { name: 'Assessment and Teaching of 21st Century Skills.pdf', type: 'file', path: `${ctedPath}/BEED/Assessment and Teaching of 21st Century Skills - Methods and Approach.pdf` },
          { name: 'Curriculum Development.pdf', type: 'file', path: `${ctedPath}/BEED/Curriculum Development.pdf` },
          { name: 'Educational Technology for Teaching and Learning.pdf', type: 'file', path: `${ctedPath}/BEED/Educational Technology for Teaching and Learning.pdf` },
          { name: 'Foundations of Special Education.pdf', type: 'file', path: `${ctedPath}/BEED/Foundations of Special Education.pdf` },
          { name: 'History of English Language.pdf', type: 'file', path: `${ctedPath}/BEED/History of English Language 5e.pdf` },
          { name: 'Introduction to Research Methodology.pdf', type: 'file', path: `${ctedPath}/BEED/Introduction to Research Methodology.pdf` },
          { name: 'Research Methodology Methods and Techniques.pdf', type: 'file', path: `${ctedPath}/BEED/Research Methodology Methods and Techniques.pdf` },
          { name: 'Teacher and the School Curriculum.pdf', type: 'file', path: `${ctedPath}/BEED/Teacher and the School Curriculum.pdf` },
          { name: 'The Teaching Profession.pdf', type: 'file', path: `${ctedPath}/BEED/The Teaching Profession.pdf` },
        ],
      },
      {
        name: 'BPE',
        type: 'folder',
        path: `${ctedPath}/BPE`,
        children: [
          { name: 'Applied Motor Control and Learning (4 files)', type: 'folder', path: `${ctedPath}/BPE/Applied Motor Control and Learning of Exercise Sports and Dance` },
          { name: 'Assessment in Learning 1 (3 files)', type: 'folder', path: `${ctedPath}/BPE/Assessment in Learning 1` },
          { name: 'Coordinated School Health Program (2 files)', type: 'folder', path: `${ctedPath}/BPE/Coordinated School Health Program` },
          { name: 'Curriculum and Assessment for PE (3 files)', type: 'folder', path: `${ctedPath}/BPE/Curriculum and Assessment for Physical Education and Health Education` },
          { name: 'Drug Education (3 files)', type: 'folder', path: `${ctedPath}/BPE/Drug Education , Consumer Health Education and Healthy Eating` },
          { name: 'Emergency Preparedness (3 files)', type: 'folder', path: `${ctedPath}/BPE/Emergency Preparedness and Safety Management` },
          { name: 'Foundation of Special Education (3 files)', type: 'folder', path: `${ctedPath}/BPE/Foundation of Special and Inclusive Education` },
          { name: 'Individual and Dual Sports (3 files)', type: 'folder', path: `${ctedPath}/BPE/Individual and Dual Sports (Racket Sports, Athletics, Martial Arts)` },
          { name: 'Philippine Government and Constitution (4 files)', type: 'folder', path: `${ctedPath}/BPE/Philippine Government and Constitution` },
          { name: 'Research 1 (3 files)', type: 'folder', path: `${ctedPath}/BPE/Research 1` },
          { name: 'Sports and Exercise Psychology (3 files)', type: 'folder', path: `${ctedPath}/BPE/Sports and Exercise Psychology` },
          { name: 'Technology Application 2 (3 files)', type: 'folder', path: `${ctedPath}/BPE/Technology Application 2` },
          { name: 'The Teaching Profession (3 files)', type: 'folder', path: `${ctedPath}/BPE/The Teaching Profession` },
        ],
      },
    ],
  },
];